// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEeKKAqw5EZjusHewmoUeOvvrDitcO8sE',
    appId: '1:476615679329:web:ab074d502f9d6611e2b920',
    messagingSenderId: '476615679329',
    projectId: 'farmerapp-137aa',
    authDomain: 'farmerapp-137aa.firebaseapp.com',
    storageBucket: 'farmerapp-137aa.firebasestorage.app',
    measurementId: 'G-8K5JCF1EM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuuJnowgy9fB3x2_meqb1WUtMpnA2ifA4',
    appId: '1:476615679329:android:6e81813b48c62ca3e2b920',
    messagingSenderId: '476615679329',
    projectId: 'farmerapp-137aa',
    storageBucket: 'farmerapp-137aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgMogmgWZyGlq8_T5ba1a-wVILF3_3isM',
    appId: '1:476615679329:ios:61242f16333c6bbae2b920',
    messagingSenderId: '476615679329',
    projectId: 'farmerapp-137aa',
    storageBucket: 'farmerapp-137aa.firebasestorage.app',
    iosBundleId: 'com.syncosolve.farmerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgMogmgWZyGlq8_T5ba1a-wVILF3_3isM',
    appId: '1:476615679329:ios:61242f16333c6bbae2b920',
    messagingSenderId: '476615679329',
    projectId: 'farmerapp-137aa',
    storageBucket: 'farmerapp-137aa.firebasestorage.app',
    iosBundleId: 'com.syncosolve.farmerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEeKKAqw5EZjusHewmoUeOvvrDitcO8sE',
    appId: '1:476615679329:web:79eea9a61a1c154ae2b920',
    messagingSenderId: '476615679329',
    projectId: 'farmerapp-137aa',
    authDomain: 'farmerapp-137aa.firebaseapp.com',
    storageBucket: 'farmerapp-137aa.firebasestorage.app',
    measurementId: 'G-9EK5FMBRRD',
  );
}